# Build
FROM golang:1.26.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /api ./cmd/api


# Runtime
FROM alpine:latest

WORKDIR /app

COPY --from=builder /api /app/api

EXPOSE 8081

CMD ["/app/api", "-p", "8081"]